### ISSUE TITLE
The planar and interleaved versions of ImagingResampleHorizontalConvolution round differently

### ISSUE THREAD

**Issue by martincmartin** [uploadcare/pillow-simd#49]
https://github.com/uploadcare/pillow-simd/blob/17582f734c2e95fe2b156faa361809961257b94f/src/libImaging/ResampleSIMDHorizontalConv.c#L292

has a `+ xmax/2` that the planar version, in the same file, doesn't have.

This affects the results, compared to a pure C loop to compute the same value.

**Comment by homm** [comment]
Indeed, the nature of `xmax` part is not clear for me. The version where 16-bit implementation was introduced already has this. However, the impact of xmax is minor, since `(1 << (coefs_precision -1)` is only half of the pixel value and xmax always about 3000 times smaller.

Fixed in the [resample](https://github.com/uploadcare/pillow-simd/tree/simd/resample) branch.
