### ISSUE TITLE
compile error on raspberry (ARM): unrecognized command line option ‘-msse4’

### ISSUE THREAD

**Issue by philippkeller** [uploadcare/pillow-simd#80]
### What did you do?

`pip3 install -U --force-reinstall pillow-simd` on a raspberry pi zero

### What did you expect to happen?

Compile and install pillow-simd

### What actually happened?

the compile step failed. I *think* the relevant section is `arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-msse4’`: in this context:

```
 arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION="7.
0.0.post3" -I/usr/include/freetype2 -I/tmp/pip-install-c7i2f9uv/pillow-simd/src/libImaging -I/tmp/pip-install-c7i2f9uv/pillow-simd -I/usr/include -I/usr/local/include -I/usr/include/python3.7m -c src/_imaging.c
-o build/temp.linux-armv6l-3.7/src/_imaging.o -msse4
  arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-msse4’
```

[Here](https://gist.github.com/philippkeller/c21a1dfa25a7bbce9077070f48c3c49b) is the full error.

my first attempt was to use `CC="cc -mavx2" pip install -U --force-reinstall pillow-simd` but `-maxvx2` seems not to be available on arm so I skipped it

### What are your OS, Python and Pillow versions?

* OS: `Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux`
* Python: Python 3.7.3
* Pillow: latest from pip (Pillow-SIMD 7.0.0.post3)

**Comment by philippkeller** [comment]
I just realize that there is also [this open issue to add arm support](https://github.com/uploadcare/pillow-simd/issues/43), so it might just not be done yet. Although, reading through some stackoverflow posts it seems that people got that running on a raspberry.

**Comment by homm** [comment]
Pillow-SIMD is not intended for ARM

**Comment by laclouis5** [comment]
> Pillow-SIMD is not intended for ARM

This is not clear from the README. 

The name "Pillow-SIMD" does not implies anything about the supported architecture since SIMD is not tied to only x86. Other array and computer vision libraries such as Numpy and OpenCV advertise a SIMD implementation without being restricted to a single architecture ([1](https://numpy.org/doc/stable/reference/simd/index.html), [2](https://docs.opencv.org/4.x/d6/dd1/tutorial_univ_intrin.html)), thus, the name "Pillow-SIMD" is confusing for people coming from those libraries, even more when Pillow-SIMD is advertised as **"Pillow-SIMD versions are 100% compatible drop-in replacements for Pillow"** which implies that Pillow-SIMD has the same compatibility as Pillow.

The x86-only compatibility is only mentioned implicitly there, but that requires knowing that AVX2 and SSE4 are specific to x86:

> SIMD stands for "single instruction, multiple data" and its essence is in performing the same operation on multiple data points simultaneously by using multiple processing elements. Common CPU SIMD instruction sets are MMX, SSE-SSE4, AVX, AVX2, AVX512, NEON.
> 
> Currently, Pillow-SIMD can be [compiled](https://github.com/uploadcare/pillow-simd/issues/80#installation) with SSE4 (default) or AVX2 support.

I suggest that the documentation could be improved by mentioning explicitly up-front the x86-only compatibility or, as mentioned in another issue, that Pillow-SIMD would simply not use SIMD on Aarch architectures.

**Comment by homm** [comment]
@laclouis5 could you check spelling and correctness?

https://github.com/uploadcare/pillow-simd/pull/132
